=== dwachmann/bvr209_83/inc/ver/versions.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- 
     $Id$
     
     Copyright (C) 2008 Dorothea Wachmann
     
     This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.
     
     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.
     
     You should have received a copy of the GNU General Public License
     along with this program.  If not, see http://www.gnu.org/licenses/.
  -->

<xs:schema xmlns="urn:bvr20983" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="urn:bvr20983" 
           elementFormDefault="qualified"
>
  <xs:annotation>
    <xs:documentation xml:lang="en">
      documents the relations between product, component and type
      and the relation of the different versions.
    </xs:documentation>
  </xs:annotation>
  
  <xs:element name="versions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="parameter" type="parameterType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="product"   type="productType" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="parameterType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="productType">
    <xs:sequence>
      <xs:element name="versionhistory"  type="versionHistoryType" minOccurs="0" maxOccurs="1"/>
      <xs:element name="name"            type="xs:string"/>
      <xs:element name="no"              type="xs:string"/>
      <xs:element name="company"         type="xs:string"/>
      <xs:element name="copyright"       type="xs:string"/>
      <xs:element name="filename"        type="xs:string"/>
      <xs:element name="patch"           type="patchType"             minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="component"       type="componentType"         minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="registryentries" type="registryEntriesType"   minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="id"        type="xs:ID"      use="required"/>
    <xs:attribute name="commit"    type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="componentType">
    <xs:sequence>
      <xs:element name="version"   type="versionType"  minOccurs="0" />
      <xs:element name="name"      type="xs:string"/>
      <xs:element name="no"        type="xs:string"    minOccurs="0" />
      <xs:element name="filename"  type="xs:string"/>
      <xs:element name="shortcut"  type="shortcutType" minOccurs="0" />
      <xs:element name="patch"     type="patchType"    minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="type"      type="typeType"     minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="typelib"   type="typelibType"  minOccurs="0"/>
    </xs:sequence>

    <xs:attribute name="id"   type="xs:ID"        use="required"/>
    <xs:attribute name="type" type="comptypeType" use="required"/>
  </xs:complexType>

  <xs:complexType name="registryEntriesType">
    <xs:sequence>
      <xs:element name="registry" type="registryType"   minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id"   type="xs:ID"        use="required"/>
  </xs:complexType>

  <xs:complexType name="registryType">
    <xs:sequence>
      <xs:element name="key"   type="registryKeyType"/>
      <xs:element name="name"  type="xs:string" minOccurs="0"/>
      <xs:element name="value" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="registryKeyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="hive" type="hiveType" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="typeType">
    <xs:sequence>
      <xs:element name="version"   type="versionType"/>
      <xs:element name="no"        type="xs:string"/>
      <xs:element name="guid"      type="xs:string"/>
    </xs:sequence>

    <xs:attribute name="id"     type="xs:ID"      use="required"/>
    <xs:attribute name="typeid" type="xs:NMTOKEN" use="required"/>
  </xs:complexType>

  <xs:complexType name="typelibType">
    <xs:sequence>
      <xs:element name="version"   type="versionType"/>
      <xs:element name="no"        type="xs:string"/>
      <xs:element name="guid"      type="xs:string"/>
      <xs:element name="patch"     type="patchType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>

    <xs:attribute name="id"     type="xs:ID"      use="required"/>
    <xs:attribute name="typeid" type="xs:NMTOKEN" use="required"/>
  </xs:complexType>

  <xs:complexType name="patchType">
    <xs:sequence>
      <xs:element name="pattern"   type="patternType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>

    <xs:attribute name="template"  type="xs:string"/>
    <xs:attribute name="filename"  type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="patternType">
    <xs:sequence>
      <xs:element name="key"      type="xs:string"/>
      <xs:element name="value"    type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="versionType">
    <xs:attribute name="major" type="xs:nonNegativeInteger" use="required"/>
    <xs:attribute name="minor" type="xs:nonNegativeInteger" />
    <xs:attribute name="fix"   type="xs:nonNegativeInteger" />
    <xs:attribute name="build" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="versionHistoryType">
    <xs:sequence>
      <xs:element name="version" type="productVersionType"  minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="productVersionType">
    <xs:sequence>
      <xs:element name="msipackagecode" type="xs:string"         minOccurs="0" />
      <xs:element name="msiproductcode" type="xs:string"         minOccurs="0" />
      <xs:element name="msicomponent"   type="xs:string"         minOccurs="0" />
      <xs:element name="msiupgradecode" type="xs:string"         minOccurs="0" />
      <xs:element name="msipatchcode"   type="xs:string"         minOccurs="0" />
      <xs:element name="msino"          type="xs:string"         minOccurs="0" />
      <xs:element name="msifeatures"    type="msiFeaturesType"   minOccurs="0" maxOccurs="1"/>
      <xs:element name="msiproperties"  type="msiPropertiesType" minOccurs="0" maxOccurs="1"/>
      <xs:element name="msipatch"       type="msiPatchType"      minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="major"    type="xs:nonNegativeInteger" use="required"/>
    <xs:attribute name="minor"    type="xs:nonNegativeInteger" use="required"/>
    <xs:attribute name="fix"      type="xs:nonNegativeInteger" use="required"/>
    <xs:attribute name="build"    type="xs:nonNegativeInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="msiFeaturesType">
    <xs:sequence>
      <xs:element name="msifeature"     type="msiFeatureType"   minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="msiFeatureType">
    <xs:sequence>
      <xs:element name="msifeature"     type="msiFeatureType"   minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="msicomponent"   type="msiComponentType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id"          type="xs:string"             use="required"/>
    <xs:attribute name="title"       type="xs:string"             use="required"/>
    <xs:attribute name="description" type="xs:string"             use="required"/>
    <xs:attribute name="directory"   type="xs:string"             />
    <xs:attribute name="level"       type="xs:nonNegativeInteger" use="required"/>
    <xs:attribute name="attribute"   type="xs:nonNegativeInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="msiPatchType">
    <xs:sequence>
      <xs:element name="msipatchmetadata"     type="msiMetadataType"   minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="msiMetadataType">
    <xs:sequence>
      <xs:element name="msiproperty"     type="msiPropertyType"   minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="msiPropertiesType">
    <xs:sequence>
      <xs:element name="msiproperty"     type="msiPropertyType"   minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="msiPropertyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="key" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="msiComponentType">
    <xs:attribute name="compid"      type="xs:string"             use="required"/>
  </xs:complexType>

  <xs:simpleType name="comptypeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="dll"/>
      <xs:enumeration value="exe"/>
      <xs:enumeration value="dir"/>
      <xs:enumeration value="file"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="hiveType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="HKEY_CURRENT_USER"/>
      <xs:enumeration value="HKEY_LOCAL_MACHINE"/>
      <xs:enumeration value="HKEY_CLASSES_ROOT"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="guidTYPE">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="revType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{1,10}|\$\{.*\}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="shortcutType">
    <xs:attribute name="featureid"   type="xs:string"             use="required"/>
    <xs:attribute name="name"        type="xs:string"             use="required"/>
    <xs:attribute name="directoryid" type="xs:string"             use="required"/>
    <xs:attribute name="icon"        type="xs:string"             use="required"/>
    <xs:attribute name="iconindex"   type="xs:nonNegativeInteger" use="required"/>
  </xs:complexType>

</xs:schema>

=== dwachmann/bvr209_83/inc/ver/versions.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- 
     $Id$
     
     Copyright (C) 2008-2009 Dorothea Wachmann
     
     This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.
     
     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.
     
     You should have received a copy of the GNU General Public License
     along with this program.  If not, see http://www.gnu.org/licenses/.
  -->
<versions xmlns="urn:bvr20983" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:bvr20983 versions.xsd">
	<parameter name="filenamepattern">#{LCase("${../../../@id}")}.${../../../v:versionhistory/v:version[1]/@major}.${../../@id}.${../../v:version/@major}</parameter>
	<parameter name="filenamepattern1">#{LCase("${../../@id}")}.${../../v:versionhistory/v:version[1]/@major}.${../../v:versionhistory/v:version[1]/@minor}.${../../v:versionhistory/v:version[1]/@fix}</parameter>
	<parameter name="guidpattern">${../../../../v:no/text()}-#{zerofill("${../../../../v:versionhistory/v:version[1]/@major}",4)}-${../../v:no/text()}-${../../@typeid}-#{zerofill("${../../v:version/@major}",4)}FFFFFFFF</parameter>
	<parameter name="typelibguidpattern">${../../../../v:no/text()}-#{zerofill("${../../../../v:versionhistory/v:version[1]/@major}",4)}-${../../v:no/text()}-${../../@typeid}-FFFFFFFFFFFF</parameter>
	<parameter name="msicomppattern">${../../../v:no/text()}-#{zerofill("${../../../v:versionhistory/v:version[1]/@major}",4)}-0103-${../../v:no/text()}-#{zerofill("${../../v:version/@major}",4)}#{zerofill("${../../v:version/@minor}",4)}#{zerofill("${../../v:version/@fix}",4)}</parameter>
	<parameter name="msicomppattern1">${../../../../v:no/text()}-#{zerofill("${../../../v:version[1]/@major}",4)}-0103-0000-0000</parameter>
	<parameter name="msiprodpattern">${../../../../v:no/text()}-#{zerofill("${../../@major}",4)}-0100-${../../v:msino/text()}-FFFFFFFFFFFF</parameter>
	<parameter name="msipackpattern">${../../../../v:no/text()}-#{zerofill("${../../@major}",4)}-0101-#{zerofill("${../../@minor}",4)}-#{zerofill("${../../@fix}",4)}FFFFFFFF</parameter>
	<parameter name="msipatchpattern">${../../../../v:no/text()}-#{zerofill("${../../@major}",4)}-0104-#{zerofill("${../../@minor}",4)}-#{zerofill("${../../@fix}",4)}FFFFFFFF</parameter>
	<parameter name="msiupdpattern">${../../../../v:no/text()}-0001-0102-FFFF-FFFFFFFFFFFF</parameter>
	<product id="BVR20983" commit="${commit}">
		<versionhistory>
			<version major="0" minor="1" fix="0" build="260">

        <msipackagecode>${msipackpattern}</msipackagecode>
				<msiproductcode>${msiprodpattern}</msiproductcode>
				<msicomponent>${msicomppattern1}</msicomponent>
				<msiupgradecode>${msiupdpattern}</msiupgradecode>
				<msipatchcode>${msipatchpattern}</msipatchcode>
				<msino>0001</msino>

        <msifeatures>
          <msifeature id="sc"         directory="TARGETDIR" level="1" attribute="0" title="Smartcard Library"      description="A COM Library to access a smartcard">
            <msicomponent compid="sc"/>
            <msicomponent compid="msgs"/>
            <msicomponent compid="res"/>
            <msicomponent compid="update"/>
            <msicomponent compid="doc"/>
            <msicomponent compid="globalregistryentries"/>
          </msifeature>
          <msifeature id="cc"         directory="TARGETDIR" level="1" attribute="0" title="Custom Control Library" description="A OCX Library with several controls">
            <msicomponent compid="cc"/>
            <msicomponent compid="msgs"/>
            <msicomponent compid="res"/>
            <msicomponent compid="update"/>
            <msicomponent compid="doc"/>
            <msicomponent compid="com"/>
          </msifeature>

          <msifeature id="demo"       directory="TARGETDIR" level="3" attribute="0" title="Demo"                   description="Demo Programs">
            <msifeature id="digiclock"  directory="TARGETDIR" level="3" attribute="0" title="A digital clock"        description="A Testfile for the digital clock control">
              <msicomponent compid="digiclock"/>
              <msicomponent compid="cc"/>
              <msicomponent compid="msgs"/>
              <msicomponent compid="res"/>
              <msicomponent compid="update"/>
              <msicomponent compid="com"/>
            </msifeature>
            <msifeature id="samples"    directory="TARGETDIR" level="3" attribute="0" title="Samples"                description="Usage Samples">
              <msicomponent compid="sample"/>
              <msicomponent compid="doc"/>
              <msicomponent compid="cc"/>
              <msicomponent compid="sc"/>
              <msicomponent compid="msgs"/>
              <msicomponent compid="res"/>
              <msicomponent compid="update"/>
              <msicomponent compid="inc"/>
              <msicomponent compid="lib"/>
            </msifeature>
          </msifeature>

          <msifeature id="tools"      directory="TARGETDIR" level="2" attribute="0" title="Tools"                  description="Tools">
            <msifeature id="lsstg"    directory="TARGETDIR"   level="2" attribute="0" title="lsstg"                  description="Display compound file structure">
              <msicomponent compid="lsstg"/>
              <msicomponent compid="inc"/>
            </msifeature>

            <msifeature id="lstypeinfo" directory="TARGETDIR" level="2" attribute="0" title="lstypeinfo"             description="Display typelib information">
              <msicomponent compid="lstypeinfo"/>
            </msifeature>
          </msifeature>
        </msifeatures>

        <msiproperties>
          <msiproperty key="ProductCode	">${../../../v:msiproductcode/text()}</msiproperty>
          <msiproperty key="ProductName">${../../../../../v:name/text()}</msiproperty>
          <msiproperty key="Manufacturer">${../../../../../v:company/text()}</msiproperty>
          <msiproperty key="ProductVersion">${../../../@major}.${../../../@minor}.0</msiproperty>
          <msiproperty key="@ProductId@">#{UCase("${../../../../../@id}")}</msiproperty>
          <msiproperty key="ARPHELPLINK">http://#{LCase("${../../../../../@id}")}.berlios.de/</msiproperty>
          <msiproperty key="ARPURLINFOABOUT">http://developer.berlios.de/projects/#{LCase("${../../../../../@id}")}</msiproperty>
          <msiproperty key="ARPURLUPDATEINFO">http://#{LCase("${../../../../../@id}")}.berlios.de/msi/</msiproperty>
          <msiproperty key="@GITURL@">git://git.berlios.de/#{LCase("${../../../../../@id}")}</msiproperty>
          <msiproperty key="UpgradeCode">#{UCase("${../../../v:msiupgradecode/text()}")}</msiproperty>
          <msiproperty key="ComponentDownload">http://#{LCase("${../../../../../@id}")}.berlios.de/update/</msiproperty>
        </msiproperties>

        <msipatch>
          <msipatchmetadata>
            <msiproperty key="ManufacturerName">${../../../../../v:company/text()}</msiproperty>
            <msiproperty key="MoreInfoURL">http://#{LCase("${../../../../../@id}")}.berlios.de/</msiproperty>
            <msiproperty key="TargetProductName">${../../../../../v:name/text()}</msiproperty>
            <msiproperty key="DisplayName">${../../../../../v:name/text()} Update</msiproperty>
            <msiproperty key="Description">#{LCase("${../../../../../@id}")} MSI Patch</msiproperty>
            <msiproperty key="AllowRemoval">1</msiproperty>
            <msiproperty key="Classification">update</msiproperty>
          </msipatchmetadata>
        </msipatch>
      </version>

      <version major="0" minor="0" fix="1" build="0">
				<msipackagecode>${msipackpattern}</msipackagecode>
				<msiproductcode>${msiprodpattern}</msiproductcode>
				<msicomponent>${msicomppattern1}</msicomponent>
				<msiupgradecode>${msiupdpattern}</msiupgradecode>
				<msipatchcode>${msipatchpattern}</msipatchcode>
				<msino>0001</msino>
			</version>
			<version major="0" minor="0" fix="0" build="0">
				<msipackagecode>${msipackpattern}</msipackagecode>
				<msiproductcode>${msiprodpattern}</msiproductcode>
				<msicomponent>${msicomppattern1}</msicomponent>
				<msiupgradecode>${msiupdpattern}</msiupgradecode>
				<msipatchcode>${msipatchpattern}</msipatchcode>
				<msino>0001</msino>
			</version>
		</versionhistory>
    
		<name>BVR2098 Suite</name>
		<no>BFE20983</no>
		<company>Dorothea Wachmann</company>
		<copyright>Copyright (c) 2008-2009 ${../../v:company/text()}</copyright>
		<filename>${filenamepattern1}</filename>
		<patch template="bvr20983volatile-ver.tmpl" filename="bvr20983volatile-ver.h">
			<pattern><key>(^#define.+verMakeDate.+")(.+)(")</key>
				<value>$1${builddate}$3</value></pattern>
			<pattern><key>(^#define.+verCommit.+")(.+)(")</key>
				<value>$1${commit}$3</value></pattern>
			<pattern><key>(^#define.+verDebugVersion.+")(.+)(")</key>
				<value>$1${debugver}$3</value></pattern>
			<pattern><key>(^#define.+verMSIProdVersion.+")(.+)(")</key>
				<value>$1${../../../../v:versionhistory/v:version[1]/@major}.${../../../../v:versionhistory/v:version[1]/@minor}.0$3</value></pattern>
			<pattern><key>(^#define.+verMSIProdCode.+")(.+)(")</key>
				<value>$1${../../../../v:versionhistory/v:version[1]/v:msiproductcode/text()}$3</value></pattern>
			<pattern><key>(^#define.+verMSIPackCode.+")(.+)(")</key>
				<value>$1${../../../../v:versionhistory/v:version[1]/v:msipackagecode/text()}$3</value></pattern>
